webtalk_init -webtalk_dir /home/justin/github/2018_fall_hardware_software_codesign_lab/ip_repo/edit_basic_integration_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_integration_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec 27 20:14:27 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6736b850-2558-4a60-a9c3-a97647f15787" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d495c939f3ab41f7a23905456bf837f7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3506.544 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124808_KB" -context "xsim\\usage"
webtalk_transmit -clientid 42937688 -regid "" -xml /home/justin/github/2018_fall_hardware_software_codesign_lab/ip_repo/edit_basic_integration_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_integration_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/justin/github/2018_fall_hardware_software_codesign_lab/ip_repo/edit_basic_integration_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_integration_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/justin/github/2018_fall_hardware_software_codesign_lab/ip_repo/edit_basic_integration_v1_0.sim/sim_1/behav/xsim/xsim.dir/tb_integration_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
