webtalk_init -webtalk_dir /home/justin/github/2018_fall_hardware_software_codesign_lab/led_detector/led_detector.sim/sim_1/behav/xsim/xsim.dir/tb_clk_div_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 24 22:47:57 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6af58cd9-fc73-4471-ab54-16c25897c5be" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "17a1eee3da014b368028a83079247773" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3747.716 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124376_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1284061007 -regid "" -xml /home/justin/github/2018_fall_hardware_software_codesign_lab/led_detector/led_detector.sim/sim_1/behav/xsim/xsim.dir/tb_clk_div_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/justin/github/2018_fall_hardware_software_codesign_lab/led_detector/led_detector.sim/sim_1/behav/xsim/xsim.dir/tb_clk_div_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/justin/github/2018_fall_hardware_software_codesign_lab/led_detector/led_detector.sim/sim_1/behav/xsim/xsim.dir/tb_clk_div_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
